# Site settings
title: Kimberley Cook
job: Web Developer and Speaker
email: kc@builtby.kim
url: builtby.kim
description: "Kimberley Cook - freelance web developer."
keywords: "public speaker, diversity and inclusion speaker, software developer, front-end developer, web developer, freelance web developer"
skills: "codebar Director & Trustee • Software Engineer • Speaker • Snowboarder • Alpinist"
meta_author: Cook Kimberley

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-82996803-1

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 6B5CA5 #6B5CA5
  primary-rgb: "0, 0, 0" #"0, 0, 0"
  secondary: 2F2963 #2F2963
  secondary-dark: 2F2963 #2F2963

# Footer settings
footer:
  copyright: Kimberley Cook
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/kimberleycook91
  - title: github
    url: http://github.com/KimberleyCook
  - title: instagram
    url: http://instagram.com/kimberleycook/

# Build settings
markdown: kramdown
permalink: pretty

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
